-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 00:55:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema esg_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esg_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS esg DEFAULT CHARACTER SET utf8 ;
USE esg ;

-- -----------------------------------------------------
-- Table `esg_dev`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_entity_id` INT NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`indicator_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`indicator_unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`indicator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL,
  `type` TINYINT NULL,
  `parent` INT NULL,
  `unit` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_indicator_parent_idx` (`parent` ASC),
  INDEX `fk_indicator_unit1_idx` (`unit` ASC),
  CONSTRAINT `fk_indicator_parent`
    FOREIGN KEY (`parent`)
    REFERENCES esg.`indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicator_unit1`
    FOREIGN KEY (`unit`)
    REFERENCES esg.`indicator_unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`template_has_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`template_has_module` (
  `template_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  PRIMARY KEY (`template_id`, `module_id`),
  INDEX `fk_template_has_module_module1_idx` (`module_id` ASC),
  INDEX `fk_template_has_module_template1_idx` (`template_id` ASC),
  CONSTRAINT `fk_template_has_module_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES esg.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_template_has_module_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES esg.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`module_has_indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`module_has_indicator` (
  `module_id` INT NOT NULL AUTO_INCREMENT,
  `indicator_id` INT NOT NULL,
  PRIMARY KEY (`module_id`, `indicator_id`),
  INDEX `fk_module_has_indicator_indicator1_idx` (`indicator_id` ASC),
  INDEX `fk_module_has_indicator_module1_idx` (`module_id` ASC),
  CONSTRAINT `fk_module_has_indicator_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES esg.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_has_indicator_indicator1`
    FOREIGN KEY (`indicator_id`)
    REFERENCES esg.`indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `esg_dev`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`user_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_roles_user1_idx` (`user_id` ASC),
  INDEX `fk_user_roles_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_roles_role1`
  FOREIGN KEY (`role_id`)
  REFERENCES esg.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_user1`
  FOREIGN KEY (`user_id`)
  REFERENCES esg.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`company_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`company_users` (
  `company_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`company_id`, `user_id`),
  INDEX `fk_company_users_company1_idx` (`company_id` ASC),
  INDEX `fk_company_users_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_company_users_company1`
  FOREIGN KEY (`company_id`)
  REFERENCES esg.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_users_user1`
  FOREIGN KEY (`user_id`)
  REFERENCES esg.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `esg_dev`.`company_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`company_template` (
  `company_id` INT NOT NULL,
  `template_id` INT NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `fk_company_template_company1_idx` (`company_id` ASC),
  INDEX `fk_company_template_user1_idx` (`template_id` ASC),
  CONSTRAINT `fk_company_template_company1`
  FOREIGN KEY (`company_id`)
  REFERENCES esg.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_template_template1`
  FOREIGN KEY (`template_id`)
  REFERENCES esg.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esg_dev`.`indicator_for_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS esg.`indicator_for_company` (
  `indicator_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`indicator_id`, `company_id`),
  INDEX `fk_indicator_for_company_indicator1_idx` (`indicator_id` ASC),
  INDEX `fk_indicator_for_company_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_indicator_for_company_company1`
  FOREIGN KEY (`company_id`)
  REFERENCES esg.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicator_for_company_indicator1`
  FOREIGN KEY (`indicator_id`)
  REFERENCES esg.`indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
